kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rpc-balance
  name: rpc-balance
  namespace: dev-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rpc-balance
  template:
    metadata:
      labels:
        app: rpc-balance
    spec:
      containers:
        - name: rpc-balance
          env:
            - name: GIN_MODE
              value: release
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE
              value: balance
          image: registry.cn-hangzhou.aliyuncs.com/pdf/go:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: tcp
          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: rpc-balance
  namespace: dev-platform
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: tcp
      port: 8081
      targetPort: 8081
  selector:
    app: rpc-balance
  clusterIP: None